-- MySQL Script generated by MySQL Workbench
-- Sun Dec 10 08:52:13 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema movieStreamingWebsite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema movieStreamingWebsite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `movieStreamingWebsite` DEFAULT CHARACTER SET utf8 ;
USE `movieStreamingWebsite` ;

-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Member` (
  `idMember` INT NOT NULL AUTO_INCREMENT,
  `userName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `profilePictureLink` VARCHAR(200) NULL,
  PRIMARY KEY (`idMember`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Admin` (
  `idMember` INT NOT NULL,
  PRIMARY KEY (`idMember`),
  INDEX `fk_Admin_Member_idx` (`idMember` ASC),
  CONSTRAINT `fk_Admin_Member`
    FOREIGN KEY (`idMember`)
    REFERENCES `movieStreamingWebsite`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Category` (
  `idCategory` INT NOT NULL AUTO_INCREMENT,
  `categoryName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Movie` (
  `idMovie` INT NOT NULL AUTO_INCREMENT,
  `movieName` VARCHAR(100) NOT NULL,
  `movieDescription` VARCHAR(300) NOT NULL,
  `moviePosterLink` VARCHAR(200) NOT NULL,
  `movieTrailerLink` VARCHAR(200) NOT NULL,
  `country` VARCHAR(45) NULL,
  `year` INT NULL,
  `length` VARCHAR(45) NULL,
  `idCategory` INT NOT NULL,
  PRIMARY KEY (`idMovie`),
  INDEX `fk_Movie_Category1_idx` (`idCategory` ASC),
  CONSTRAINT `fk_Movie_Category1`
    FOREIGN KEY (`idCategory`)
    REFERENCES `movieStreamingWebsite`.`Category` (`idCategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Rating` (
  `Rating` INT NOT NULL,
  `idMember` INT NOT NULL,
  `idMovie` INT NOT NULL,
  INDEX `fk_Rating_Member1_idx` (`idMember` ASC),
  INDEX `fk_Rating_Movie1_idx` (`idMovie` ASC),
  PRIMARY KEY (`idMovie`, `idMember`),
  CONSTRAINT `fk_Rating_Member1`
    FOREIGN KEY (`idMember`)
    REFERENCES `movieStreamingWebsite`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rating_Movie1`
    FOREIGN KEY (`idMovie`)
    REFERENCES `movieStreamingWebsite`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Favorite` (
  `idMember` INT NOT NULL,
  `idMovie` INT NOT NULL,
  PRIMARY KEY (`idMember`, `idMovie`),
  INDEX `fk_Favorite_Movie1_idx` (`idMovie` ASC),
  CONSTRAINT `fk_Favorite_Member1`
    FOREIGN KEY (`idMember`)
    REFERENCES `movieStreamingWebsite`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Favorite_Movie1`
    FOREIGN KEY (`idMovie`)
    REFERENCES `movieStreamingWebsite`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Link` (
  `idLink` INT NOT NULL,
  `movieLink` VARCHAR(200) NOT NULL,
  `serverName` VARCHAR(45) NOT NULL,
  `idMovie` INT NOT NULL,
  PRIMARY KEY (`idLink`),
  INDEX `fk_Link_Movie1_idx` (`idMovie` ASC),
  CONSTRAINT `fk_Link_Movie1`
    FOREIGN KEY (`idMovie`)
    REFERENCES `movieStreamingWebsite`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`Log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`Log` (
  `idLog` INT NOT NULL,
  `logTime` DATETIME NOT NULL,
  PRIMARY KEY (`idLog`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`WatchLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`WatchLog` (
  `idLog` INT NOT NULL,
  `idMovie` INT NOT NULL,
  `idMember` INT NOT NULL,
  PRIMARY KEY (`idLog`),
  INDEX `fk_WatchLog_Movie1_idx` (`idMovie` ASC),
  INDEX `fk_WatchLog_Member1_idx` (`idMember` ASC),
  CONSTRAINT `fk_WatchLog_Log1`
    FOREIGN KEY (`idLog`)
    REFERENCES `movieStreamingWebsite`.`Log` (`idLog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WatchLog_Movie1`
    FOREIGN KEY (`idMovie`)
    REFERENCES `movieStreamingWebsite`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_WatchLog_Member1`
    FOREIGN KEY (`idMember`)
    REFERENCES `movieStreamingWebsite`.`Member` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `movieStreamingWebsite`.`AdminLog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movieStreamingWebsite`.`AdminLog` (
  `idLog` INT NOT NULL,
  `actionTaken` VARCHAR(200) NOT NULL,
  `Admin_idMember` INT NOT NULL,
  PRIMARY KEY (`idLog`),
  INDEX `fk_AdminLog_Admin1_idx` (`Admin_idMember` ASC),
  CONSTRAINT `fk_AdminLog_Log1`
    FOREIGN KEY (`idLog`)
    REFERENCES `movieStreamingWebsite`.`Log` (`idLog`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AdminLog_Admin1`
    FOREIGN KEY (`Admin_idMember`)
    REFERENCES `movieStreamingWebsite`.`Admin` (`idMember`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
